# Generated by Django 5.0.3 on 2024-04-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cometarios',
            new_name='Comentarios',
        ),
    ]
